version: '2'

services:
  apollo-quick-start:
    image: apollo-quick-start
    container_name: apollo-quick-start
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8070:8070"
    volumes:
      - /tmp/logs:/opt/logs
    links:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - dbdata

  dbdata:
    image: alpine:latest
    container_name: dbdata
    volumes:
      - /var/lib/mysql
